### ISSUE TITLE
Colab should warn when there are insufficient GPU resources.

### ISSUE THREAD

**Issue by ghost** [dribnet/clipit#11]
```
NameError                                 Traceback (most recent call last)
<ipython-input-6-e07db4d0b3d4> in <module>()
     40 
     41 settings = clipit.apply_settings()
---> 42 clipit.do_init(settings)
     43 clipit.do_run(settings)

/content/clipit/clipit.py in do_init(args)
    373             drawer = PixelDrawer(args.size[0], args.size[1], args.do_mono, [40, 40], scale=args.pixel_scale)
    374         else:
--> 375             drawer = PixelDrawer(args.size[0], args.size[1], args.do_mono, scale=args.pixel_scale)
    376     else:
    377         drawer = VqganDrawer(args.vqgan_model)

NameError: name 'PixelDrawer' is not defined
```

**Comment by ziofil** [comment]
I get the same

**Comment by dribnet** [comment]
I think this is due to google being more stingy lately with the T4 GPUs needed to run the models. (either that - or perhaps you are not running the first cell twice as instructed?)

I've relabelled the issue appropriately and will try to patch up the co-labs so that it gives a big warning when it has insufficient GPU memory to initialise correctly.

**Comment by dribnet** [comment]
I have now implemented this in the latest PixelDraw colabs. Please check it out and see if it beeps and warns you during setup. If this is insufficient, happy to reopen the issue.
