### ISSUE TITLE
Parameter Explanations

### ISSUE THREAD

**Issue by aelizie** [dribnet/clipit#16]
Hi, I maybe have missed it, but are there any docs on the parameters? Some I can puzzle together from the code, but others are a little bit more mysterious to me, like spot-prompts or number of cuts for example.

**Comment by dribnet** [comment]
Most of the parameters aren't meant for public use - they are more the byproduct of several iterations of one-off experiments. I also inherited several from @nerdyrodent's version of the code which I don't use or even fully understand myself.

However, I think this is a relevant concern since even the relevant ones are not well documented so let's leave this issue open and try to address this. For starters: `num_cuts` is an important one and is loosely speaking the "Batch size". In general, increasing this is very helpful in converging quicker but it takes up precious GPU memory to do so.

**Comment by dribnet** [comment]
I'm closing this issue here because have recently moved the core library to the [pixray]( https://github.com/dribnet/pixray) repo. However I'm happy to re-open it there as I think having at least a markdown cheat-sheet of working parameters would be helpful.
