### ISSUE TITLE
Runtime Error for Pixray

### ISSUE THREAD

**Issue by z3Nsk1Fh5a** [dribnet/clipit#22]
Swirl Demo

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-c70d0fa10b87> in <module>()
     70 
     71 settings = pixray.apply_settings()
---> 72 pixray.do_init(settings)
     73 pixray.do_run(settings)
     74 

1 frames
/usr/local/lib/python3.7/dist-packages/torch/jit/_script.py in fail(self, *args, **kwargs)
    912     def _make_fail(name):
    913         def fail(self, *args, **kwargs):
--> 914             raise RuntimeError(name + " is not supported on ScriptModules")
    915 
    916         return fail

RuntimeError: requires_grad_ is not supported on ScriptModules

**Comment by dribnet** [comment]
This is due to a torchtext change upstream. There is a patch available:

```
  !pip install torch==1.9.0+cu102 torchtext==0.10.0 torchvision==0.10.0+cu102 torch-optimizer==0.1.0 -f https://download.pytorch.org/whl/torch/ -f https://download.pytorch.org/whl/torchvision/
```

which when added to setup will fix this. I am looking to see if there is a less heavyweight version of this and will update the notebooks.

**Comment by dribnet** [comment]
Let me patch the swirl notebook and you can retry. Just a few minutes...

**Comment by z3Nsk1Fh5a** [comment]
Thank you kindly.  Still learning to navigate Python.  Your notebooks and updates are an inspiration.

**Comment by dribnet** [comment]
I believe that is fixed now. Reload [the colab page](https://colab.research.google.com/github/dribnet/clipit/blob/master/demos/Pixray_Swirl_Demo.ipynb) and let me know if you have any issues.

**Comment by dribnet** [comment]
Seems to be working for me in testing - but feel free to reopen if there are any problems.

**Comment by manofiga** [comment]
Hi there, this issue seems to be still going on.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-4-15d132434906>](https://localhost:8080/#) in <module>()
     69 # pixray.add_settings(iterations=500, display_every=50)
     70 
---> 71 settings = pixray.apply_settings()
     72 pixray.do_init(settings)
     73 pixray.do_run(settings)

[/content/pixray/pixray.py](https://localhost:8080/#) in apply_settings()
   1567 
   1568     vq_parser = setup_parser(vq_parser)
-> 1569     class_table[settings_core.drawer].add_settings(vq_parser)
   1570 
   1571     if len(global_pixray_settings) > 0:

KeyError: 'pixel'

**Comment by Ilhem331** [comment]
settings = pixray.apply_settings()
pixray.do_init(settings)
pixray.do_run(settings)

AttributeError: module 'PIL.TiffTags' has no attribute 'IFD'
